# Generated by Django 5.2.7 on 2025-10-12 08:35

import todoApp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('priority', models.CharField(choices=[('H', 'High'), ('M', 'Medium'), ('L', 'Low')], default='M', max_length=1)),
                ('deadline', models.DateField(blank=True, null=True, validators=[todoApp.models.validate_no_past_date])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
